[general]
hostname = "xen1"
log_level = "info" # debug, info, trace, warn, error

[[storage.local]]
enabled = true
name = "local_nfs"
path = "/var/run/sr-mount/a69d1361-c718-d46e-63fd-49cde4db1fca/exports"

[monitoring.mail]
enabled = true
smtp_server = "192.168.100.164"
smtp_port = 1025
smtp_user = ""
smtp_password = ""
smtp_from = "xenbak@localhost"
smtp_to = ["asdf@test.test"]
[monitoring.healthchecks]
enabled = true
api_key = "VkSpHYVtXfkQRuhojpeUrKAwBexF-oTq"
server = "http://192.168.100.164:8000"
grace = 7200
max_retry = 5

[[jobs]]
enabled = true
name = "test"
schedule = "0 */3 * * * *"
tag_filter = ["backup"]          # Only backup VMs with the given tags
tag_filter_exclude = ["exclude"] # Exclude VMs with the given tags
timeout = 3600                   # Timeout for the backup job in seconds
concurrency = 3                  # Number of concurrent backups
retention = 3                    # Retention period in days
compression = "zstd"             # Compression type:  gzip, zstd or none
