[general]
log-level = "info" # debug, info, trace, warn, error

[storage]
[storage.local]
enabled = true
path = "asdf"
[storage.s3]
enabled = true
bucket = ""
endpoint = ""
access_key = ""

[monitoring]
[monitoring.mail]
enabled = true
smtp_server = ""
smtp_port = 587
smtp_user = ""
smtp_password = ""
smtp_from = ""
smtp_to = [""]
[monitoring.healthchecks]
enabled = true
project_url = ""
timeout = 5

[[jobs]]
enabled = true
name = "test"
schedules = ["*/1 * * * *"]
storage = ["local", "s3"]         # s3, local -> see [storage] section
tag_filter = ["backup"]           # Only backup VMs with the given tags
tag_filter_exclude = ["database"] # Exclude VMs with the given tags
timeout = 3600                    # Timeout for the backup job in seconds
concurrency = 1                   # Number of concurrent backups
retention = 7                     # Retention period in days
compression = "none"              # Compression type: none, gzip, zstd
limit_bandwidth = 0               # Limit the bandwidth in MiB/s (0 = no limit)
