[general]
hostname = "xen1"
log_level = "info" # debug, info, trace, warn, error

[monitoring.mail]
enabled = true
smtp_server = "192.168.100.164"
smtp_port = 1025
smtp_user = ""
smtp_password = ""
smtp_from = "xenbak@localhost"
smtp_to = ["asdf@test.test"]
[monitoring.healthchecks]
enabled = true
api_key = "VkSpHYVtXfkQRuhojpeUrKAwBexF-oTq"
server = "http://192.168.100.164:8000"
grace = 7200
max_retry = 5

[[xen]]
enabled = true
name = "xen1"
username = ""
server = "127.0.0.1"
password = ""
port = 443

# storage handler for local paths (e.g. NFS, CIFS, local filesystem). does not need temporary space
[[storage.local]]
enabled = true
name = "local"
path = "/var/run/sr-mount/a69d1361-c718-d46e-63fd-49cde4db1fca/exports"
compression = "zstd"                                                    # gzip, zstd or none 
retention = 3                                                           # Number of backups to keep

# storage handler for local borg repositories (e.g. NFS, CIFS, local filesystem)
[[storage.borg_local]]
enabled = false
name = "borg"
repo_base_path = "/mnt/backup"
temp_dir = "/tmp"
encryption = "repokey-blake2"
compression = "zstd"
retention = 3


[[jobs]]
enabled = true
name = "test"
schedule = "0 */2 * * * *"
tag_filter = ["backup"]          # Only backup VMs with the given tags
tag_filter_exclude = ["exclude"] # Exclude VMs with the given tags
concurrency = 1                  # Number of concurrent backups
storages = ["local", "borg"]     # Storage to use for the backup
xen_hosts = ["xen1"]             # Xen hosts to backup
