[general]
log_level = "debug" # debug, info, trace, warn, error

[[storage.local]]
enabled = true
name = "local_nfs"
path = "/mnt/backup/"

[monitoring.mail]
enabled = true
smtp_server = ""
smtp_port = 587
smtp_user = ""
smtp_password = ""
smtp_from = ""
smtp_to = [""]
[monitoring.healthchecks]
enabled = true
project_url = ""
timeout = 5

[[jobs]]
enabled = true
name = "test"
schedule = "0 */1 * * * *"
storages = ["local_nfs"]
tag_filter = ["backup"]          # Only backup VMs with the given tags
tag_filter_exclude = ["exclude"] # Exclude VMs with the given tags
timeout = 3600                   # Timeout for the backup job in seconds
concurrency = 2                  # Number of concurrent backups
retention = 7                    # Retention period in days
compression = "none"             # Compression type: none, gzip, zstd
limit_bandwidth = 0              # Limit the bandwidth in MiB/s (0 = no limit)
