name: Common Build Steps

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      artifact-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Install dependencies
        run: |
          sudo apt-get update -yqq
          sudo apt-get install -yqq --no-install-recommends build-essential
          sudo apt-get install -yqq musl-tools
          rustup target add x86_64-unknown-linux-musl

      - name: Build project
        run: cargo build --release --target ${{ inputs.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: target/${{ inputs.target }}/release/xenbakd
