name: Rust

on:
  push:
    branches: ["ci"]
  pull_request:
    branches: ["ci"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: cache cargo dependencies
        id: cache-cargo-deps
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-deps
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
